version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: blood_donation_database
      POSTGRES_USER: blood_donation_database_user
      POSTGRES_PASSWORD: fgJD0oY6uDLs3CgKCax6gChOOupf5V3Q
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blood_donation_database
      SPRING_DATASOURCE_USERNAME: blood_donation_database_user
      SPRING_DATASOURCE_PASSWORD: fgJD0oY6uDLs3CgKCax6gChOOupf5V3Q